version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      - MYSQL_URL=mysql
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=belajar
      - MYSQL_PORT=3307
    ports:
      - "3307:3306"
    networks:
      - java_network
  springboot-multidb:
    container_name: springboot-multidb
    image: springboot-multidb:latest
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/belajar
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - mysql
    networks:
      - java_network

networks:
  java_network:
    name: java_network
